# Site settings
baseurl = "https://example.com/"
title = "Hugo Story Theme"
theme = "story"
paginate = 5

[[menu.social]]
  name = "GitHub"
  title = "fab fa-github-square"
  url = "https://github.com/xaprb/story/"

[params]
  author = "Baron Schwartz"
  classes = []

[outputs]
  home = ["HTML", "JSON", "RSS"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
  taxonomyTerm = ["HTML", "RSS"]
